// <auto-generated />
using System;
using MayTheFourth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MayTheFourth.Migrations
{
    [DbContext(typeof(MayTheFourthDataContext))]
    [Migration("20240429094831_Teste")]
    partial class Teste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("FilmeNavesEstelares", b =>
                {
                    b.Property<int>("FilmesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NavesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmesId", "NavesId");

                    b.HasIndex("NavesId");

                    b.ToTable("FilmeNavesEstelares");
                });

            modelBuilder.Entity("FilmePlaneta", b =>
                {
                    b.Property<int>("FilmesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanetasId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmesId", "PlanetasId");

                    b.HasIndex("PlanetasId");

                    b.ToTable("FilmePlaneta");
                });

            modelBuilder.Entity("FilmeVeiculo", b =>
                {
                    b.Property<int>("FilmesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VeiculosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FilmesId", "VeiculosId");

                    b.HasIndex("VeiculosId");

                    b.ToTable("FilmeVeiculo");
                });

            modelBuilder.Entity("MayTheFourth.Entities.Dtos.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataLancamento")
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("DataLancamento");

                    b.Property<string>("Diretor")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Diretor");

                    b.Property<int>("Episodio")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Episodio");

                    b.Property<string>("Produtor")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Produtor");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.ToTable("Filme", (string)null);
                });

            modelBuilder.Entity("MayTheFourth.Entities.Dtos.NavesEstelares", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CapacidadeCarga")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("CapacidadeCarga");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Classe");

                    b.Property<string>("ClassificacaoHiperdrive")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("ClassificacaoHiperdrive");

                    b.Property<string>("Comprimento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Comprimento");

                    b.Property<string>("Consumiveis")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Consumiveis");

                    b.Property<string>("Custo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Custo");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Fabricante");

                    b.Property<string>("Mglt")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Mglt");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Modelo");

                    b.Property<string>("Passageiros")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Passageiros");

                    b.Property<string>("Tripulacao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Tripulacao");

                    b.Property<string>("VelocidadeMaxima")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("VelocidadeMaxima");

                    b.HasKey("Id");

                    b.ToTable("NavesEstelares", (string)null);
                });

            modelBuilder.Entity("MayTheFourth.Entities.Dtos.Personagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Altura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Altura");

                    b.Property<string>("CorCabelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("CorCabelo");

                    b.Property<string>("CorOlhos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("CorOlhos");

                    b.Property<string>("CorPele")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("CorPele");

                    b.Property<string>("DataNascimento")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("DataNascimento");

                    b.Property<int?>("FilmeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Genero");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Nome");

                    b.Property<string>("Peso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Peso");

                    b.Property<int?>("PlanetaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FilmeId");

                    b.HasIndex("PlanetaId");

                    b.ToTable("Personagem", (string)null);
                });

            modelBuilder.Entity("MayTheFourth.Entities.Dtos.Planeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Clima")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Clima");

                    b.Property<string>("Diametro")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Diametro");

                    b.Property<string>("Gravidade")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Gravidade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Nome");

                    b.Property<string>("PeriodoOrbital")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("PeriodoOrbital");

                    b.Property<string>("PeriodoRotacao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("PeriodoRotacao");

                    b.Property<string>("Populacao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Populacao");

                    b.Property<string>("SuperficieAquatica")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("SuperficieAquatica");

                    b.Property<string>("Terreno")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Terreno");

                    b.HasKey("Id");

                    b.ToTable("Planeta", (string)null);
                });

            modelBuilder.Entity("MayTheFourth.Entities.Dtos.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CapacidadeCarga")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("CapacidadeCarga");

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Classe");

                    b.Property<string>("Comprimento")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Comprimento");

                    b.Property<string>("Consumiveis")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Consumiveis");

                    b.Property<string>("Custo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Custo");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Fabricante");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Modelo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Nome");

                    b.Property<string>("Passageiros")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Passageiros");

                    b.Property<string>("Tripulacao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Tripulacao");

                    b.Property<string>("VelocidadeMaxima")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("VelocidadeMaxima");

                    b.HasKey("Id");

                    b.ToTable("Veiculo", (string)null);
                });

            modelBuilder.Entity("FilmeNavesEstelares", b =>
                {
                    b.HasOne("MayTheFourth.Entities.Dtos.Filme", null)
                        .WithMany()
                        .HasForeignKey("FilmesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MayTheFourth.Entities.Dtos.NavesEstelares", null)
                        .WithMany()
                        .HasForeignKey("NavesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmePlaneta", b =>
                {
                    b.HasOne("MayTheFourth.Entities.Dtos.Filme", null)
                        .WithMany()
                        .HasForeignKey("FilmesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MayTheFourth.Entities.Dtos.Planeta", null)
                        .WithMany()
                        .HasForeignKey("PlanetasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmeVeiculo", b =>
                {
                    b.HasOne("MayTheFourth.Entities.Dtos.Filme", null)
                        .WithMany()
                        .HasForeignKey("FilmesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MayTheFourth.Entities.Dtos.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MayTheFourth.Entities.Dtos.Personagem", b =>
                {
                    b.HasOne("MayTheFourth.Entities.Dtos.Filme", null)
                        .WithMany("Personagens")
                        .HasForeignKey("FilmeId");

                    b.HasOne("MayTheFourth.Entities.Dtos.Planeta", null)
                        .WithMany("Personagens")
                        .HasForeignKey("PlanetaId");
                });

            modelBuilder.Entity("MayTheFourth.Entities.Dtos.Filme", b =>
                {
                    b.Navigation("Personagens");
                });

            modelBuilder.Entity("MayTheFourth.Entities.Dtos.Planeta", b =>
                {
                    b.Navigation("Personagens");
                });
#pragma warning restore 612, 618
        }
    }
}
